#
# Makefile for all kinds of Fingerprint
#

obj-$(CONFIG_GOODIX_FINGERPRINT) += goodix/
obj-$(CONFIG_FPC_FINGERPRINT) += fpc/
# [liguanxiong start] Add for secondary fingerprint module Sunwave sw9251
obj-$(CONFIG_SUNWAVE_FINGERPRINT_SW9251) += sunwavecorp/
obj-$(CONFIG_SUNWAVE_FINGERPRINT_SW9651) += sunwavecorp/tee/
# [liguanxiong end]
